[profile.default]
src = "src"
test = "test"
script = "script"
out = "out"
libs = ["lib"]

# Compiler
solc = "0.8.24"
evm_version = "cancun"
via_ir = true

# Optimizer
optimizer = true
optimizer_runs = 200

# Logging
verbosity = 2
gas_reports = ["*"]

# Safety
ffi = false

# Filesystem permissions
[[profile.default.fs_permissions]]
access = "read"
path = "./"

# RPC endpoints
[rpc_endpoints]
base = "https://mainnet.base.org"

# Fork profile
[profile.fork]
block_number = 14650000
